### ISSUE TITLE
SDK cant't be found

### ISSUE THREAD

**Issue by lucaingold** [vippsas/java-sdk#32]
Hello
Is it possible that the sdk is not published in the mentioned maven repository? I always get an error message from gradle that the sdk cannot be found. Thanks, luca

**Comment by eirikv** [comment]
Hi! The SDK is published in the mentioned repository, but unfortunately GitHub does not allow unauthenticated access to GitHub Packages at the moment. 🙄 So you need to add your GitHub credentials to you gradle or maven setup install it.

We are looking into publishing the SDK elsewhere, since this is an inconvenient requirement from GitHub.

* https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages
* https://github.com/orgs/community/discussions/26634
